name: Maven CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 设置 JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: 缓存 Maven 仓库
    - name: Cache Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    # 在执行 mvn clean install 步骤前添加此步骤来设置 MAVEN_OPTS
    - name: Set MAVEN_OPTS
      run: |
       echo "MAVEN_OPTS=--add-modules jdk.compiler --add-reads jdk.compiler=ALL-UNNAMED" >> $GITHUB_ENV
    # Step 4: 安装依赖并构建项目
    - name: Build project
      run: mvn clean install

    # Step 5: 运行测试
    - name: Run Tests
      run: mvn test

    # Step 6: 可选：生成测试覆盖率报告
    - name: Generate Coverage Report
      run: mvn jacoco:report
