name: SonarQube Analysis
on:
  workflow_dispatch:
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build with Maven
        run: mvn clean package
        env:
          MAVEN_OPTS: >
            --add-opens jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED
            --add-opens jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
            --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
            --add-opens jdk.compiler/com.sun.tools.javac=ALL-UNNAMED
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        with:
          args: >
            -Dsonar.projectKey=springboot-project
            -Dsonar.projectName=springboot-project
            -Dsonar.java.binaries=**/target/classes
