name: SonarQube Analysis
on:
  workflow_dispatch:  # 允许手动触发
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package -Dmaven.compiler.args="--add-opens jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED"
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        with:
          args: >
            -Dsonar.projectKey=springboot-project
            -Dsonar.projectName=Spring Boot Project
            -Dsonar.projectVersion=1.0
            -Dsonar.sources=.
            -Dsonar.java.binaries=target/classes
